version: '3.6'

volumes:
    pg_data:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local

services:
    postgres:
        image: postgres:16.0-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5411:5432"
        environment:
            POSTGRES_USER: able
            POSTGRES_PASSWORD: able
            POSTGRES_DB: able
