version: '3.6'

volumes:
    pg_data:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local

services:
    postgres:
        image: postgres:16.0-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5411:5432"
        environment:
            POSTGRES_USER: able
            POSTGRES_PASSWORD: able
            POSTGRES_DB: able
    
    api:
        build:
            context: .
            dockerfile: docker/Api.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://able:able@postgres:5432/able
    
    web:
        build:
            context: .
            dockerfile: docker/Web.Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - postgres
            - api
