apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: github-deploy-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: User
      name: able-dev@able-dev.iam.gserviceaccount.com
      apiGroup: rbac.authorization.k8s.io
