apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka
    namespace: able-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
                - name: kafka
                  image: bitnami/kafka:3.3.2
                  ports:
                      - containerPort: 9092
                      - containerPort: 29092
                      - containerPort: 9093
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "200m"
                      limits:
                          memory: "1Gi"
                          cpu: "500m"
                  env:
                      - name: BITNAMI_DEBUG
                        value: "true"
                      - name: KAFKA_CFG_NODE_ID
                        value: "1"
                      - name: KAFKA_CFG_PROCESS_ROLES
                        value: "broker,controller"
                      - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
                        value: "1@127.0.0.1:9093"
                      - name: KAFKA_CFG_LISTENERS
                        value: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092"
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: "PLAINTEXT://kafka:9092,EXTERNAL://kafka-external:29092"
                      - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
                        value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
                      - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
                        value: "CONTROLLER"
                      - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
                        value: "PLAINTEXT"
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
                        value: "true"
            volumes:
                - name: kafka-configmaps
                  configMap:
                      name: kafka-controller-configuration

---

apiVersion: v1
kind: Service
metadata:
    name: kafka
    namespace: able-dev
spec:
    selector:
        app: kafka
    ports:
        - name: kafka
          port: 9092
          targetPort: 9092
