apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access
  namespace: able-dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: able-dev-secret-access
  namespace: able-dev
subjects:
  - kind: User
    name: able-dev@able-dev.iam.gserviceaccount.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-access
  apiGroup: rbac.authorization.k8s.io
